namespace: sylvain

## External access to the service in a cluster
ingress:
  name: "block-time-manager"
  serviceNameFront: "btm-frontend"
  serviceNameBack: "btm-backend"
  tls: true
  className: "nginx"
  host: "block-time-manager.cluster-2022-9.dopolytech.fr"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production


## MongoDB Chart Bitnami
mongodb:
  global:
    namespaceOverride: sylvain
  auth:
    usernames: 
    - "admin"
    databases:
    - "time-manager"
    existingSecret: "btm-secrets-sylvain" 
    

## Deployments
deployments: 
- name: btm-backend
  replicaCount: 1
  image:
    repository: sylvainpierrot/btm-backend
    pullPolicy: Always
    tag: latest  
  containerPort: "5000"
  env:
  - name: PORT
    value: "5000"
  - name: BASE_URL
    value: https://block-time-manager.cluster-2022-9.dopolytech.fr
  - name: MONGODB_URL
    valueFrom:
      secretKeyRef:
        name: btm-secrets-sylvain
        key: mongodb-url
- name: btm-frontend
  replicaCount: 1
  image:
    repository: sylvainpierrot/btm-frontend
    pullPolicy: Always
    tag: latest
  containerPort: "80"
  env:
  - name: REACT_APP_BASE_URL
    value: https://block-time-manager.cluster-2022-9.dopolytech.fr


## Services
services:
- name: btm-backend
- name: btm-frontend


## Ressources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi